### ISSUE TITLE
BOP: PM Agenda and Meeting Minutes

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/BOP#264]
### Overview
This issue tracks the agenda for our weekly meetings

#### Issue Template
```
## [Date ]  Meeting Agenda

### Prework to prep for meeting
- [ ] #

### Recurring items: Happens on the ________ meeting
 - [ ] review any issues that are in the [new issue approval column]
 - [ ] Accountability and Support Check.
    - [ ] Review assignments for each Team member
       - [ ] [Name of Person]
- [ ] finish adding labels to the issue that are still missing them (see audit links above)
- [ ] review issues with [epic label] and define how to break down further
- [ ] Review to see if there are any members to Onboard or Offboard 
      - [ ]  #

### New Items
- [ ] 
- [ ] Carry over Items to next meeting that don't get addressed

### FYIs
-

### Notes from Meeting

### Task Items
```

### Links to other agenda issues for your team 
(so that you can easily post on their agendas items that come up at yours)

### Previous Meetings (link to each comment with the date)

**Comment by ExperimentsInHonesty** [comment]
## 2023-10-22  Meeting Agenda

### Prework to prep for meeting
- [ ] #  

### Recurring items: Happens on the ________ meeting
 - [ ] review any issues that are in the [new issue approval column]
 - [ ] Accountability and Support Check.
    - [ ] Review assignments for each Team member
       - [ ] [Name of Person]
- [ ] finish adding labels to the issue that are still missing them (see audit links above)
- [ ] review issues with [epic label] and define how to break down further
- [ ] Review to see if there are any members to Onboard or Offboard 
      - [ ]  #

### New Items
- [ ] 
- [ ] Carry over Items to next meeting that don't get addressed

### FYIs
-

### Notes from Meeting

### Task Items
-  Make agendas for Each subteam
   - [ ] DEV/PM
   - [ ] DEV
   - [ ] UI/UX/PM
   - [ ] UI/UX
   - [ ] Data/PM
   - [ ] ALL

**Comment by Estherchuks** [comment]
##  2023-10-29 Meeting Agenda

### Prework to prep for meeting
- [ ] #  

### Recurring items: Happens on the ________ meeting
 - [ ] review any issues that are in the [new issue approval column]
 - 
 - 
 - [ ] Accountability and Support Check.
    - [ ] Review assignments for each Team member
       - [ ] [Name of Person]
- [ ] finish adding labels to the issue that are still missing them (see audit links above)
- [ ] review issues with [epic label] and define how to break down further
- [ ] Review to see if there are any members to Onboard or Offboard 
      - [ ]  #

### New Items
- [ ] 
- [ ] Carry over Items to next meeting that don't get addressed

### FYIs
-

### Notes from Meeting

### Task Items

**Comment by ExperimentsInHonesty** [comment]
## [Date ]  Meeting Agenda

### Prework to prep for meeting
- [ ] #  

### Recurring items: Happens on the ________ meeting
 - [ ] review any issues that are in the [new issue approval column]
 - [ ] Accountability and Support Check.
    - [ ] Review assignments for each Team member
       - [ ] [Esther](https://github.com/hackforla/BOP/issues/assigned/Estherchuks)
       - [ ] [Ksenia](https://github.com/hackforla/BOP/issues/assigned/ksenia)
       - [ ] [Bonnie](https://github.com/hackforla/BOP/issues/assigned/ExperimentsInHonesty)
- [ ] finish adding labels to the issue that are still missing them (see audit links above)
- [ ] review issues with [epic label] and define how to break down further
- [ ] Review to see if there are any members to Onboard or Offboard 
      - [ ]  #

### New Items
- [ ] Onboard Ksenia #265 
- [ ] Carry over Items to next meeting that don't get addressed

### FYIs
-

### Notes from Meeting

### Task Items

**Comment by ExperimentsInHonesty** [comment]
## 2024-01-28 Meeting Agenda

### Prework to prep for meeting
- [ ] #  

### Recurring items: Happens on the ________ meeting
 - [ ] review any issues that are in the [new issue approval column]
 - [ ] Accountability and Support Check.
    - [ ] Review assignments for each Team member
       - [ ] [Esther](https://github.com/hackforla/BOP/issues/assigned/Estherchuks)
       - [ ] [Ksenia](https://github.com/hackforla/BOP/issues/assigned/ksenia)
       - [ ] [Bonnie](https://github.com/hackforla/BOP/issues/assigned/ExperimentsInHonesty)
       - [ ] [Aleiya](https://github.com/hackforla/BOP/issues/assigned/ag2463)
- [ ] finish adding labels to the issue that are still missing them (see audit links above)
- [ ] review issues with [epic label] and define how to break down further
- [ ] Review to see if there are any members to Onboard or Offboard 
      - [ ]  #

### New Items
- [ ] 
- [ ] Carry over Items to next meeting that don't get addressed

### FYIs
-

### Notes from Meeting

### Task Items

**Comment by Estherchuks** [comment]
## 2024-02-11  Meeting Agenda

### Prework to prep for meeting
- [ ] #  

### Recurring items: Happens on the ________ meeting
 - [ ] review any issues that are in the [new issue approval column]
 - [ ] Accountability and Support Check.
    - [ ] Review assignments for each Team member
       - [ ] [Esther](https://github.com/hackforla/BOP/issues/assigned/Estherchuks)
       - [ ] [Ksenia](https://github.com/hackforla/BOP/issues/assigned/ksenia)
       - [ ] [Bonnie](https://github.com/hackforla/BOP/issues/assigned/ExperimentsInHonesty)
- [ ] finish adding labels to the issue that are still missing them (see audit links above)
- [ ] review issues with [epic label] and define how to break down further
- [ ] Review to see if there are any members to Onboard or Offboard 
      - [ ]  #

### New Items
- [ ] 
- [ ]  Finish Onboarding Sanju
     - [ ] Add to Vault
     - [ ] Add to Github
     - [ ] 1password
     

### FYIs
-

### Notes from Meeting

### Task Items

**Comment by ExperimentsInHonesty** [comment]
## 2024-02-18 Meeting Agenda

### Prework to prep for meeting
- [ ] #262   

### Recurring items: Happens on the ________ meeting
 - [ ] review any issues that are in the [new issue approval column]
 - [ ] Accountability and Support Check.
    - [ ] Review assignments for each Team member
       - [ ] [Esther](https://github.com/hackforla/BOP/issues/assigned/Estherchuks)
       - [ ] [Ksenia](https://github.com/hackforla/BOP/issues/assigned/ksenia)
       - [ ] [Bonnie](https://github.com/hackforla/BOP/issues/assigned/ExperimentsInHonesty)
- [ ] finish adding labels to the issue that are still missing them (see audit links above)
- [ ] review issues with [epic label] and define how to break down further
- [ ] Review to see if there are any members to Onboard or Offboard 
      - [ ]  #

### New Items
- [ ]  Finish [Onboarding PM](https://github.com/hackforla/BOP/issues/263)  Sanju
     - [ ] Add to Vault
     - [ ] Add to Github
- [ ] Review the spreadsheet that Thad K was going to revise and get back to Jenny.
- [ ] Carry over Items to next meeting that don't get addressed

### FYIs
-

### Notes from Meeting

### Task Items

**Comment by ExperimentsInHonesty** [comment]
## 2024-02-18 Meeting Agenda

### Prework to prep for meeting
- [ ] # 262

### Recurring items: Happens on the ________ meeting
 - [ ] review any issues that are in the [new issue approval column]
 - [ ] Accountability and Support Check.
    - [ ] Review assignments for each Team member
       - [ ] [Esther](https://github.com/hackforla/BOP/issues/assigned/Estherchuks)
       - [ ] ~[Ksenia](https://github.com/hackforla/BOP/issues/assigned/ksenia)~
       - [ ] [Bonnie](https://github.com/hackforla/BOP/issues/assigned/ExperimentsInHonesty)
       - [ ] [Sanju](https://github.com/hackforla/BOP/issues/assigned/sanjumv)
- [ ] finish adding labels to the issue that are still missing them (see audit links above)
- [ ] review issues with [epic label] and define how to break down further
- [ ] Review to see if there are any members to Onboard or Offboard 
      - [ ]  #

### Previous agenda items
- [ ] BW: Finish [Onboarding PM](https://github.com/hackforla/BOP/issues/263) Sanju
     - [ ] Add to Vault
     - [ ] Add to Github
- [ ] BW: Review the spreadsheet that Thad K was going to revise and get back to Jenny.
- [ ] BW: Reach out to Ksenia
- [ ] BW: This project needs its milestones reviewed

### New Items
- [ ] 
- [ ] Carry over Items to next meeting that don't get addressed

### FYIs
-

### Notes from Meeting

### Task Items

**Comment by Estherchuks** [comment]
## 2024-03-03 Meeting Agenda

### Role Call
       - [ ] [Esther](https://github.com/hackforla/BOP/issues/assigned/Estherchuks)
       - [ ] ~[Ksenia](https://github.com/hackforla/BOP/issues/assigned/ksenia)~
       - [ ] [Bonnie](https://github.com/hackforla/BOP/issues/assigned/ExperimentsInHonesty)
       - [ ] [Sanju](https://github.com/hackforla/BOP/issues/assigned/sanjumv)
       - [ ] [Aleiya](https://github.com/hackforla/BOP/issues/assigned/ag2463)
       
### Prework to prep for meeting
- [ ] #262

### Recurring items: Happens on the ________ meeting
 - [ ] review any issues that are in the [new issue approval column]
 - [ ] Accountability and Support Check.
    - [ ] Review assignments for each Team member
       - [ ] [Esther](https://github.com/hackforla/BOP/issues/assigned/Estherchuks)
       - [ ] ~[Ksenia](https://github.com/hackforla/BOP/issues/assigned/ksenia)~
       - [ ] [Bonnie](https://github.com/hackforla/BOP/issues/assigned/ExperimentsInHonesty)
       - [ ] [Sanju](https://github.com/hackforla/BOP/issues/assigned/sanjumv)
       - [ ] [Aleiya](https://github.com/hackforla/BOP/issues/assigned/ag2463)
- [ ] finish adding labels to the issue that are still missing them (see audit links above)
- [ ] review issues with [epic label] and define how to break down further
- [ ] Review to see if there are any members to Onboard or Offboard 
      - [ ]  #

### New Items
- [ ] BW: Reach out to Ksenia
 - [ ]  BW: This project needs its milestones reviewed

### FYIs
-

### Notes from Meeting

### Task Items

**Comment by Estherchuks** [comment]
1. ## 2024-03-10 Meeting Agenda

### Role Call
       - [ ] [Esther](https://github.com/hackforla/BOP/issues/assigned/Estherchuks)
       - [ ] ~[Ksenia](https://github.com/hackforla/BOP/issues/assigned/ksenia)~
       - [ ] [Bonnie](https://github.com/hackforla/BOP/issues/assigned/ExperimentsInHonesty)
       - [ ] [Sanju](https://github.com/hackforla/BOP/issues/assigned/sanjumv)
       - [ ] [Aleiya](https://github.com/hackforla/BOP/issues/assigned/ag2463)
       
### Prework to prep for meeting
- [ ] #262

### Recurring items: Happens on the ________ meeting
 - [ ] review any issues that are in the [new issue approval column]
 - [ ] Accountability and Support Check.
    - [ ] Review assignments for each Team member
       - [ ] [Esther](https://github.com/hackforla/BOP/issues/assigned/Estherchuks)
       - [ ] ~[Ksenia](https://github.com/hackforla/BOP/issues/assigned/ksenia)~
       - [ ] [Bonnie](https://github.com/hackforla/BOP/issues/assigned/ExperimentsInHonesty)
       - [ ] [Sanju](https://github.com/hackforla/BOP/issues/assigned/sanjumv)
       - [ ] [Aleiya](https://github.com/hackforla/BOP/issues/assigned/ag2463)
- [ ] finish adding labels to the issue that are still missing them (see audit links above)
- [ ] review issues with [epic label] and define how to break down further
- [ ] Review to see if there are any members to Onboard or Offboard 
      - [ ]  #

### Previous Agenda Itema
-[ ] Reach out to Ksenia
-[ ]This project needs its milestones reviewed

### New Items
- [ ] 
- [ ] Carry over Items to next meeting that don't get addressed

### FYIs
-

### Notes from Meeting

### Task Items

**Comment by Estherchuks** [comment]
## 2024-04-14

 Meeting Agenda

 
 ### Prework to prep for meeting
- [ ] #262

### Recurring items: Happens on the ________ meeting
 - [ ] review any issues that are in the [new issue approval column]
 - [ ] Accountability and Support Check.
    - [ ] Review assignments for each Team member
       - [ ] [Esther](https://github.com/hackforla/BOP/issues/assigned/Estherchuks)
       - [ ] ~[Ksenia](https://github.com/hackforla/BOP/issues/assigned/ksenia)~
       - [ ] [Bonnie](https://github.com/hackforla/BOP/issues/assigned/ExperimentsInHonesty)
       - [ ] [Sanju](https://github.com/hackforla/BOP/issues/assigned/sanjumv)
       - [ ] [Aleiya](https://github.com/hackforla/BOP/issues/assigned/ag2463)
- [ ] finish adding labels to the issue that are still missing them (see audit links above)
- [ ] review issues with [epic label] and define how to break down further
- [ ] Review to see if there are any members to Onboard or Offboard 
      - [ ]  #

### New Items
- [ ] Ask Liz about this #261 
- [ ] [https://www.figma.com/file/XEr9WwIWKCVLaUZh5VQhXw/BOP-Design?type=design&node-id=5725%3A51&mode=design&t=TZL3nW8ILGcxtv2m-1]

### FYIs
-

### Notes from Meeting

### Task Items

**Comment by ExperimentsInHonesty** [comment]
## 2024-04-28 Meeting Agenda

### Role Call
       - [ ] [Esther](https://github.com/hackforla/BOP/issues/assigned/Estherchuks)
       - [ ] [Bonnie](https://github.com/hackforla/BOP/issues/assigned/ExperimentsInHonesty)
       - [ ] [Sanju](https://github.com/hackforla/BOP/issues/assigned/sanjumv)
       - [ ] [Aleiya](https://github.com/hackforla/BOP/issues/assigned/ag2463)
       
### Prework to prep for meeting
- [ ] #262

### Recurring items: Happens on the ________ meeting
 - [ ] review any issues that are in the [new issue approval column]
 - [ ] Accountability and Support Check.
    - [ ] Review assignments for each Team member
       - [ ] [Esther](https://github.com/hackforla/BOP/issues/assigned/Estherchuks)
       - [ ] [Bonnie](https://github.com/hackforla/BOP/issues/assigned/ExperimentsInHonesty)
       - [ ] [Sanju](https://github.com/hackforla/BOP/issues/assigned/sanjumv)
       - [ ] [Aleiya](https://github.com/hackforla/BOP/issues/assigned/ag2463)
- [ ] finish adding labels to the issue that are still missing them (see audit links above)
- [ ] review issues with [epic label] and define how to break down further
- [ ] Review to see if there are any members to Onboard or Offboard 
      - [ ]  #

### New Items
- [ ] 
- [ ] Carry over Items to next meeting that don't get addressed

### FYIs
-

### Notes from Meeting

### Task Items

**Comment by ExperimentsInHonesty** [comment]
## [Date ]  Meeting Agenda

### Role Call
- [ ]  Esther
- [ ]  Bonnie
- [ ]  Sanju
- [ ]  Aleiya

       
### Prework to prep for meeting
- [ ] #262

### Recurring items: Happens on the ________ meeting
 - [ ] review any issues that are in the [new issue approval column]
 - [ ] Accountability and Support Check.
    - [ ] Review assignments for each Team member
       - [ ] [Esther](https://github.com/hackforla/BOP/issues/assigned/Estherchuks)
       - [ ] [Bonnie](https://github.com/hackforla/BOP/issues/assigned/ExperimentsInHonesty)
       - [ ] [Sanju](https://github.com/hackforla/BOP/issues/assigned/sanjumv)
       - [ ] [Aleiya](https://github.com/hackforla/BOP/issues/assigned/ag2463)
- [ ] finish adding labels to the issue that are still missing them (see audit links above)
- [ ] review issues with [epic label] and define how to break down further
- [ ] Review to see if there are any members to Onboard or Offboard 
      - [ ]  #

### New Items
- [ ] review the [BOP Processes and Practices Data [INTERNAL], sheet 6](https://docs.google.com/spreadsheets/d/1ZyeIDeHnzwjnkfYuhzeUZQo5tYXpbdnF-HKqN8cZy_A/edit#gid=295107937) and transfer the new values to the main sheet and finish categorizing the items
- [ ] Carry over Items to next meeting that don't get addressed

### FYIs
-

### Notes from Meeting

### Task Items

**Comment by Rabia2219** [comment]
- https://github.com/civictechindex/BOP/issues/289
