### ISSUE TITLE
Onboard and Offboard: UI/UX Lead

### ISSUE THREAD

**Issue by sanjumv** [hackforla/BOP#280]

**Comment by sanjumv** [comment]
#### Onboard
- [ ] Internship shared Google Drive
   - [ ] Add to drive as Manager
- [ ] Internship - PII Google Drive
   - [ ] Add to drive as Manager
- [ ] Roster
  - [ ] Send link
  - [ ] Team member adds themselves
- [ ] GitHub
     - [ ] Add to team write team
        - [ ] Change membership to maintainer
     - [ ] Add to read vault
        - [ ] Change membership to maintainer
     - [ ] Confirm that their name is on their Github 
     - [ ] Assign them to the issue #101, add them to role call and accountability check 
     - [ ] Assign them to the issue #62, add them to role call and accountability check  
     - [ ] Assign them to the issue #315, add them to role call and accountability check
- [ ] Add to Google calendar invites
   - [ ] Tuesday Design System Meeting (if necessary)
      - [ ] not needed 
   - [ ] Tuesday BA meeting (if necessary)
      - [ ] not needed
   - [ ] Tuesday UX Research meeting (if necessary)
      - [ ] not needed
   - [ ] Thursday All-team meeting
- [ ] Figma
  - [ ] invite
  - [ ] acceptance
- [ ] 1password 
     - [ ] invitation
     - [ ] acceptance
     - [ ] add to vaults
       - [ ] Internship- ux program
       - [ ] Zoom vault
- [ ] Grant access to Zoom Meeting Setup spreadsheet
- [ ] Update team page on Wiki
   - [How to activate-inactivate team members from roster and wiki](https://github.com/hackforla/internship/wiki/How-to-activate-inactivate-team-members-from-roster-and-wiki) 
- [ ] Add to email address(s)
   - [ ] internship-ux@hackforla.org
- [ ] Train how to 
   - [ ] login to team email account
   - [ ] setup chrome extension shortcut
   - [ ] use zoom spreadsheet, vault and accounts
   - [ ] calendar invite

**Comment by sanjumv** [comment]
#### Offboard
- [ ] Remove from Google calendar invite
   - [ ] Monday PM meeting
   - [ ] Tuesday BA meeting
   - [ ] Tuesday UX Research meeting
   - [ ] Wednesday PM meeting (ad-hoc)
   - [ ] Thursday All-team meeting
- [ ] 1password setup
   - [ ] remove from team vaults
   - [ ] Internship - ux program
   - [ ] Zoom vault
- [ ] Revoke access from Zoom Meeting Setup spreadsheet
- [ ] Internship shared Google Drive
   - [ ] demote to viewer
- [ ] Internship - PII Google Drive
   - [ ] Remove access to the drive
- [ ] Roster
  - [ ] mark as inactive
- [ ] GitHub
     - [ ] demote member to read only team and remove from write team
     - [ ] Un Assign them to the issue #101, remove them from role call and accountability check  
     - [ ] Un Assign them to the issue #62, remove them from role call and accountability check   
     - [ ] Un-assign them to the issue #315, remove them from the roll call and accountability check
     - [ ] Check their Assignment status on the Issue tab, to make sure they are no longer assigned to any issues
- [ ] Figma
  - [ ] remove from team
- [ ] Update team page on wiki
  - [How to activate-inactivate team members from roster and wiki](https://github.com/hackforla/internship/wiki/How-to-activate-inactivate-team-members-from-roster-and-wiki)
- [ ] Remove from email address(s)
   - [ ] internship-ux@hackforla.org

**Comment by sanjumv** [comment]
### **Resources for Onboarding**

Add the links below each item

Name of project's Slack channel(s)
bop
Times/days of all your team's meetings
All Monday 11:30 am PST/2:30 pm EST/ 8:30 pm WAT
[Team roster link](https://docs.google.com/spreadsheets/d/1-0SQyyvZGACrXdh6LKRk1EN2rD2qaHU21eGZ7-O0vwE)
[Check for public](https://github.com/orgs/hackforla/people)
Name of project's 1password vault(s)
BOP (for PMs and research)
BOP - Dev/Data
BOP - UI/UX (for design)
Project's HfLA email address(s)
[bop@hackforla.org](mailto:bop@hackforla.org)
[How to forward email addresses to team members](https://github.com/hackforla/product-management/wiki/Forward-emails-to-team-members)
[Project's Google Drive link](https://drive.google.com/drive/folders/0AHm1jtnPQgtkUk9PVA)
[GitHub Team URL](https://github.com/orgs/hackforla/teams?query=bop)
[Write team](https://github.com/orgs/hackforla/teams/bop-write/)
[Read team](https://github.com/orgs/hackforla/teams/bop/members)
[Figma](https://www.figma.com/files/team/1165704529667395862/HfLA%3A-BOP?fuid=775836858007206739)
